[package]
name = "helloworld"
version = "0.1.0"
edition = "2018"
authors = ["guozhongqiu"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
